name: Testing React-App
run-name: ${{ github.actor }} is executing the workflow
env:
  NODE_VERSION: 22
  REPO_NAME: pact-react-ui-service
  PACT_BROKER_BASE_URL: https://vietnam-national-university.pactflow.io
  PACT_BROKER_TOKEN: FhetDP4tQXfYaQPLl6QrBw
  PACTICIPANT: NodeBackend

on:
  push:
    branches:
      - master
jobs:
  test-and-publish-contract:
    runs-on: ubuntu-latest
    # Execute steps to test the project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      # Xin chao
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Consumer contract test
        run: npx jest test/create-user-consumer.pact.test.js

      - name: Print the commit's SHA of Git commit
        run: echo ${{ github.sha }}

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: Publish contract
        run: npx pact-broker publish pact/pacts --consumer-app-version "3.0.6" 
          --branch "main" --broker-base-url ${{env.PACT_BROKER_BASE_URL}} --broker-token ${{env.PACT_BROKER_BASE_URL}}

  can-i-deploy:
    needs: test-and-publish-contract
    runs-on: ubuntu-latest
    steps:
      - name: can-i-deploy
        run: npx pact-broker can-i-deploy --pacticipant ${{env.PACTICIPANT}} \
          --broker-base-url ${{env.PACT_BROKER_BASE_URL}} -k ${{env.PACT_BROKER_BASE_URL}} --version 1.0.0 \
          --retry-while-unknown 30 \
          --retry-interval 10

  release:
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}