name: Testing React-App
run-name: ${{ github.actor }} is executing the workflow
env:
  NODE_VERSION: 22
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    # Execute steps to test the project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Print the ref of Git commit
        run: echo ${{ github.ref }}
#      - name: Login to Dockerhub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Validate build configuration
#        uses: docker/build-push-action@v6
#        with:
#          call: check
#
#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pact-ui-service:latest